# Generated by Django 5.0.1 on 2024-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endyear", models.IntegerField()),
                ("intensity", models.IntegerField(verbose_name=range(0, 20))),
                ("sector", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("insight", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("startyear", models.IntegerField()),
                ("impact", models.CharField(max_length=100)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("published", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100)),
                ("relevance", models.IntegerField(verbose_name=range(0, 20))),
                ("pestle", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("likelihood", models.IntegerField(verbose_name=range(0, 20))),
            ],
        ),
    ]
