# Generated by Django 5.0.1 on 2024-01-18 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="intensity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Value cannot be less than 1!"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=20, message="Value cannot be greater than 20!"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="likelihood",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Value cannot be less than 1!"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=20, message="Value cannot be greater than 20!"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="relevance",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Value cannot be less than 1!"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=20, message="Value cannot be greater than 20!"
                    ),
                ]
            ),
        ),
    ]
