# Generated by Django 5.0.1 on 2024-01-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_alter_data_intensity_alter_data_likelihood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="endyear",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
