# Generated by Django 5.0.1 on 2024-01-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_alter_data_endyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="startyear",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
