# Generated by Django 5.0.1 on 2024-01-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_data_mongodb_id_alter_data_intensity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="added",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="published",
            field=models.DateTimeField(),
        ),
    ]
