# Generated by Django 5.0.1 on 2024-01-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_alter_data_added_alter_data_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
